#%RAML 1.0 DataType
type: object
properties:
  FirstName:
    type: string
    required: true
    example: "Bob"
  LastName:
    type: string
    required: true
    example: "Frederick"
  DOB:
    type: string
    required: true
    example: "06/21/1980"
  Gender:
    type: string
    required: true
    example: "M"
  Title:
    type: string
    required: true
    example: "Manager"
      
      
      
            